### ISSUE TITLE
Looking forward to script and cfg_file on training a Lookup-FFN transformer.

### ISSUE THREAD

**Issue by ningding-o** [mlpen/LookupFFN#1]
As I try to run the training script following the command line in README
"""
python3 main.py --config cfgs/roberta/small-512/prenorm.py
"""

A bug occurs: There is no "RobertaEmbeddings" and there is no file "postnorm.py"

Traceback (most recent call last):
  File "/home/ma-user/work/lookup_ffn/main.py", line 139, in <module>
    main(config)
  File "/home/ma-user/work/lookup_ffn/main.py", line 85, in main
    model = import_from_string(config.model.pl_module)(config, data)
  File "/home/ma-user/work/lookup_ffn/src/roberta/tasks/mlm.py", line 90, in __init__
    self.model = RobertaForMLM(self.model_config)
  File "/home/ma-user/work/lookup_ffn/src/roberta/tasks/mlm.py", line 37, in __init__
    self.roberta = import_from_string(config.encoder_type)(config)
  File "/home/ma-user/work/lookup_ffn/src/args.py", line 35, in import_from_string
    exec(f"import {location}")
  File "<string>", line 1, in <module>
  File "/home/ma-user/work/lookup_ffn/src/roberta/models/prenorm.py", line 5, in <module>
    from .postnorm import RobertaEmbeddings
ModuleNotFoundError: No module named 'src.roberta.models.postnorm'

**Comment by ningding-o** [comment]
So I copy the "class RobertaEmbeddings" from https://github.com/mlpen/mra-attention/blob/main/src/roberta/models/postnorm.py#L6, and now it runs normally.

But the training script and config file are for a standard transformer.
It's NOT for a transformer with Lookup-FFN.
Could you please upload the script and cfg_file on how to run a Lookup-FFN transformer (on GPU and CPU) ?

**Comment by mlpen** [comment]
Hello, thanks for interesting at this work and pointing out the bugs. I updated the code and uploaded the config files for lookups. 
Thank you!

**Comment by ningding-o** [comment]
Thanks for the update, now I can train from scratch normally using the new cfg file.
The C code for bh4 and fast_hadamard_transform can be compiled by ninja on a computer with cuda-11.8.
However, the ninja failed to compile the C code on a computer with cuda-10.2 version.
May I ask how to select the specified cuda version when running the "torch.utils.cpp_extension.load" part ?

**Comment by mlpen** [comment]
Sorry for the late response. 
I am not sure how to change the cuda version for compilation. Are there any specific reasons for this specific version? Can't the code be run on cuda-11.8?

**Comment by ningding-o** [comment]
I update the cuda to 12.1 and torch to 2.0.1, and the codes run smoothly ~ Appreciate
